# Generated by Django 2.1.7 on 2021-12-28 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211228_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 28, 16, 33, 26, 166136)),
        ),
    ]
